# Generated by Django 6.0.2 on 2026-02-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='genra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.genra'),
        ),
    ]
